- src/components/Footer.js
- src/components/Logo.js
- src/components/Navigation.js
- src/index.css
> Navigation Updated

- package.json
- src/App.jsx
- src/api/api.js
- src/common/utils/ProtectedRoute.js
- src/components/ProfileMenu/ProfileMenu.jsx
- src/index.js
- src/pages/ArticleEditor/ArticleEditor.js
- src/pages/Profile/Profile.jsx
- src/redux/articleEditor/articleEditorSlice.js
- src/redux/auth/authSlice.js
- src/store.js
- yarn.lock
- Added editor.js
- Added upload image plugin
- Added get image
- Addeed Delete image
- Added code and other contect blocks
> Added editor.js

- src/components/Navigation/Navigation.jsx
> Feature001

- src/App.jsx
- src/components/Navigation/Navigation.jsx
- src/pages/Auth/components/Login/Login.jsx
- src/pages/Auth/components/Register/Register.jsx
- src/redux/auth/authSlice.js
- src/utils/UserService.js
> fixed registration issue

- package.json
- src/App.jsx
- src/components/Navigation/Navigation.jsx
- src/index.css
- src/pages/write/Write.jsx
- src/pages/write/custom_Scrollbar.css
- src/pages/write/editorComponent/EditorComponent.jsx
- src/pages/write/editorComponent/customScrollbar.css
- src/pages/write/editorComponent/editorTools.js
- yarn.lock
> added editorjs

- README.md
Changed the readme file, added how to run on system.
> added how to run on system

- src/App.jsx
- src/components/Footer/Footer.js
- src/components/Footer/FooterComponent.css
- src/components/Footer/PrivacyPolicyPage.js
- src/components/Footer/TermsOfUse.js
Added privacy policy page. (Footer)
#94
Add any other context or information about the pull request here.
> add: privacy policy page

- api_documentation/auth.yaml
Please provide a summary of the changes you've made in the React JavaScript code for The Monkeys UI.
Please link the issue ticket number that this PR solves.
If applicable, add screenshots to help explain your changes in the UI. Please ensure that the screenshots do not contain any sensitive information.
Add any other context or information about the pull request here.
> Api documentation

- src/components/Contributors/Members.jsx
- src/components/Footer/FooterComponent.css
- src/components/Navigation/Navigation.jsx
- src/pages/Auth/components/Login/Login.jsx
- src/pages/Auth/components/Register/Register.jsx
- src/redux/auth/authSlice.js
- src/utils/Constant.js
Please provide a summary of the changes you've made in the React JavaScript code for The Monkeys UI.
Please link the issue ticket number that this PR solves.
If applicable, add screenshots to help explain your changes in the UI. Please ensure that the screenshots do not contain any sensitive information.
Add any other context or information about the pull request here.
> Exclamation added

- src/components/Navigation/Navigation.jsx
Please provide a summary of the changes you've made in the React JavaScript code for The Monkeys UI.
Please link the issue ticket number that this PR solves.
If applicable, add screenshots to help explain your changes in the UI. Please ensure that the screenshots do not contain any sensitive information.
Add any other context or information about the pull request here.
> fix hamburger for desktop scrrens

- .vscode/settings.json
- package-lock.json
- package.json
- tsconfig.json
- yarn.lock
In this pull request, I've initiated the migration process to TypeScript by incorporating the TypeScript compiler and essential type declarations for React and ReactDOM.
1. **Installed TypeScript:**
- Added TypeScript to the project dependencies.
2. **Added TypeScript Type Declarations:**
- Included the following type declaration packages to ensure TypeScript support:
- `"typescript": "^5.3.3"` 
- `"@types/react": "^18.2.47"`
- `"@types/react-dom": "^18.2.18"`
- Laying the groundwork for migrating the project to TypeScript, enhancing static typing and overall development experience.
- Please review and provide feedback on the changes made to facilitate a smooth migration process.
Feel free to provide any additional context or information about this specific part of the pull request.
> Ts migrate

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
In this PR I have added templates for:
1. Feature Request
2. Bug Report
3. Pull Request
> Added templates for Issues and Pull Requests

- .gitignore
- README.md
With this PR I have updated the README.md file according to the current configuration and tech stack
Fixes
#170 
NIL
> Updated Readme File

- src/app/layout.tsx
> site verification bug resolved

- src/app/robots.ts
> robots issue resolved

- src/components/icon.tsx
- src/components/input/PasswordInput.tsx
- src/components/modals/login/PasswordInput.tsx
- src/components/modals/login/Step2.tsx
- Create component `PasswordInput.tsx` that toggles the visibility of the password input box in the login page 
- Implement created component in `Step2.tsx`
Fixes #192 
- Go to login page
- Input password
- Toggle visibility of password with eye symbol
> Create a password visibility component 

- src/app/api/auth/[...nextauth]/route.ts
- src/components/branding/HomeBanner.tsx
- src/components/buttons/createButton.tsx
- src/components/modals/login/Step2.tsx
- src/components/modals/login/Step3.tsx
- src/components/modals/login/Step4.tsx
- src/constants/modal.ts
> - Loading added for login and register

- src/components/modals/index.tsx
Code fix for redirect issue
redirection problem
> Fix: fixed bug for modal redirect

- src/app/news/components/news/Source1Card.tsx
> Issue Resolved NULL IMAGE

- src/app/create/page.tsx
- src/app/edit/[blogId]/page.tsx
- src/app/globals.css
- src/components/editor/index.tsx
- src/config/editor/editorjs.config.ts
> Image issue resolved

- src/app/[username]/components/profile/EditDialog.tsx
- src/app/[username]/components/profile/ProfileCard.tsx
- src/app/[username]/components/profile/ProfileSection.tsx
- src/app/[username]/components/profile/TopicsCard.tsx
- src/app/settings/components/Profile.tsx
- src/components/profileImage.tsx
- src/components/skeletons/profileSkeleton.tsx
In this PR I have added changes to the profile and topics card in profile page.
NIL
> Added Changes To Profile Section

- src/app/[username]/components/Blogs.tsx
- src/app/[username]/components/Drafts.tsx
- src/app/[username]/components/Saved.tsx
- src/app/blog/[blogId]/components/blog/BlogInfoSection.tsx
- src/app/blog/[blogId]/components/blog/BlogTopics.tsx
- src/app/explore-topics/components/AddTopicForm.tsx
- src/app/feed/components/LatestBlogs.tsx
- src/app/feed/components/SelectedBlogs.tsx
- src/app/feed/layout.tsx
- src/app/feed/page.tsx
- src/app/globals.css
- src/app/settings/components/Profile.tsx
- src/components/blog/cards/BlogCard.tsx
- src/components/blog/cards/BlogRecommendationCard.tsx
- src/components/blog/cards/FeedBlogCard.tsx
- src/components/blog/getBlogContent.tsx
- src/components/layout/navbar/profileDropdown.tsx
- src/components/modals/publish/PublishModal.tsx
- src/components/profileImage.tsx
- src/components/ui/calendar.tsx
- src/components/ui/select.tsx
- src/hooks/blog/useGetBookmarkedBlogs.ts
- src/hooks/user/useGetAllTopics.ts
- src/services/blog/blogTypes.ts
- src/services/category/categoryTypes.ts
- tailwind.config.ts
With this PR I have added the bookmarked blogs in profile page and fixed topics selection in publish modal.
NIL
> Added Bookmarked Blogs, Fixed Publish Modal

- src/app/create/page.tsx
- src/app/edit/[blogId]/page.tsx
- src/app/explore-topics/components/AddTopicForm.tsx
- src/app/explore-topics/components/CategoryButton.tsx
- src/config/editor/editorjs.config.ts
- src/constants/api.ts
> Fixed API URL Issue

- package-lock.json
- package.json
- src/app/create/page.tsx
- src/app/edit/[blogId]/page.tsx
- src/app/globals.css
- src/components/blog/getBlogContent.tsx
- src/components/editor/editor.d.ts
- src/components/layout/navbar/NotificationDropdown.tsx
- src/config/editor/editorjs.config.ts
- src/config/editor/editorjs_readonly.config.ts
- tailwind.config.ts
> Added Code Block In Editor

- src/app/[username]/components/profile/ProfileCard.tsx
- src/app/news/page.tsx
> Added Fix For Update Username Dialog Auth 

- src/components/modals/index.tsx
Adds focus trap to fix modal focus 
Fixes #254 
https://github.com/user-attachments/assets/ed3f02ec-e7de-40c2-a712-05a326d111a9
> feat: add focus trap to modal

- src/app/[username]/components/profile/UpdateUsernameDialog.tsx
- src/components/modals/login/Step1.tsx
- src/components/modals/login/Step2.tsx
- src/components/themeSwitch.tsx
- src/components/ui/button.tsx
- src/components/ui/input.tsx
> fix: ux improvement

- src/app/[username]/components/Blogs.tsx
- src/app/[username]/components/Drafts.tsx
- src/app/[username]/components/Saved.tsx
- src/app/[username]/components/profile/ProfileCard.tsx
- src/app/[username]/components/profile/ProfileSection.tsx
- src/app/[username]/components/profile/TopicsCard.tsx
- src/app/[username]/components/profile/UpdateDialog.tsx
- src/app/[username]/page.tsx
- src/app/blog/components/blog/BlogRecommendations.tsx
- src/app/explore-topics/components/AddTopicDialog.tsx
- src/app/feed/components/FollowingBlogs.tsx
- src/app/feed/components/LatestBlogs.tsx
- src/app/feed/components/SelectedBlogs.tsx
- src/app/feed/page.tsx
- src/app/globals.css
- src/app/not-found.tsx
- src/components/blog/LikesCount.tsx
- src/components/blog/cards/BlogCard.tsx
- src/components/blog/cards/BlogRecommendationCard.tsx
- src/components/blog/cards/FeedBlogCard.tsx
- src/components/cards/SocialCard.tsx
- src/components/layout/footer/index.tsx
- src/components/layout/navbar/WSNotificationDropdown.tsx
- src/components/skeletons/blogSkeleton.tsx
- src/components/skeletons/searchSkeleton.tsx
- src/components/skeletons/userSkeleton.tsx
- src/components/ui/button.tsx
- src/constants/social.ts
- src/hooks/user/useUser.ts
- src/lib/schema/blog.ts
With this PR I have added following tabs in blog feed and some other UI improvements.
> Added Following Tab In Blog Feed

- src/app/[username]/components/profile/ProfileSection.tsx
- src/app/blog/components/blog/BlogReactions.tsx
- src/app/feed/components/BlogsByInterest.tsx
- src/app/feed/components/BlogsByTopic.tsx
- src/app/feed/page.tsx
- src/components/user/buttons/followButton.tsx
- src/components/user/cards/ProfileInfoCard.tsx
In this PR I've fixed the issue of continuous loading state been shown in the interests tab and prevent api calls for unauthenticated users.
Fixed issues:
#266  
#265 
> Fixed Interests tab loading state + prevent api calls when unauthenticated 

- src/app/sitemap.ts
> SEO Changes

- src/app/blog/[slug]/page.tsx
- src/app/blog/components/BlogReactions.tsx
- src/app/feed/components/blogFeed/BlogFeed.tsx
- src/app/feed/components/blogFeed/LatestBlogs.tsx
- src/app/feed/components/followingFeed/FollowingBlogs.tsx
- src/app/library/components/Bookmarks.tsx
- src/app/topics/[topic]/components/BlogsByTopic.tsx
- src/components/badges/topicBadge.tsx
- src/components/blog/LikesCount.tsx
- src/components/blog/ReactionsInfo.tsx
- src/components/blog/actions/BlogActionsDropdown.tsx
- src/components/blog/actions/BlogShareDialog.tsx
- src/components/blog/actions/DeleteBlogDialog.tsx
- src/components/blog/actions/EditBlogDialog.tsx
- src/components/blog/buttons/BookmarkButton.tsx
- src/components/blog/buttons/LikeButton.tsx
- src/components/blog/buttons/RemoveBookmarkButton.tsx
- src/components/blog/cards/BlogCard.tsx
- src/components/blog/cards/FeedBlogCard.tsx
- src/components/blog/cards/ShowcaseBlogCard.tsx
- src/components/icon.tsx
- src/components/user/cards/ProfileCard.tsx
- src/components/user/cards/ProfileInfoCard.tsx
- src/components/user/dialogs/ConnectionsDialog.tsx
- src/hooks/user/useBookmarkStatus.ts
- src/hooks/user/useLikeStatus.ts
In this PR I've introduced following changes:
1. Removed bookmark button from feed card
2. Added share dialog in feed card
3. Improved edit blog dialog
NIL
> Improvements in Feed and Profile

- src/app/auth/components/ForgotPasswordForm.tsx
- src/app/auth/forgot-password/page.tsx
> Forgot password flow

- src/app/blog/[slug]/page.tsx
- src/app/blog/components/BlogReactions.tsx
- src/app/blog/components/BlogTopics.tsx
- src/app/feed/components/showcaseFeed/ShowcaseFeed.tsx
- src/app/globals.css
- src/app/sitemap.ts
- src/app/topics/explore/page.tsx
- src/components/badges/topicBadge.tsx
- src/components/blog/cards/ShowcaseBlogCard.tsx
- src/components/editor/preview.tsx
- src/components/icon.tsx
- src/components/modals/publish/PublishModal.tsx
- src/components/skeletons/blogSkeleton.tsx
- src/components/skeletons/userSkeleton.tsx
- src/components/user/userInfo.tsx
- src/constants/modal.ts
- src/constants/topics.ts
- src/hooks/user/useUserConnections.ts
With this PR I have changed the max count for the topics we can add to a blog and also update the feed and blog page accordingly.
NIL
> Updated max count for blog topics + connections list fixes

- src/constants/footer.ts
This PR adds a mailto link to redirect users to write a mail for support. This is a temporary fix, before the backend apis are ready for contact us form
> feat: add link to contact us in footer

- src/services/api/axiosFileInstance.ts
Fixes upload profile pic error.
> feat: include credentials in file instance

- .github/workflows/delete-merged-branches.yml
> feat(workflow): add GitHub Action to auto-delete merged branches

- __tests__/src/app/auth/components/ForgotPasswordForm.test.tsx
- src/app/auth/components/forms/ForgotPasswordForm.tsx
Fix forgot password submit interaction
Before
[Screencast from 2025-03-02 11-36-41.webm](https://github.com/user-attachments/assets/1f792dc8-0a3b-4c6d-b2e1-9ae3db4c9791)
After
[Screencast from 2025-03-02 11-35-28.webm](https://github.com/user-attachments/assets/96b349df-e725-48c5-a56c-73ea77dfe963)
> fix: forgot password submit disabled button

- src/app/auth/google/callback/page.tsx
- src/app/auth/login/page.tsx
- src/components/layout/navbar/profileDropdown.tsx
- src/services/auth/auth.ts
> feat: enable google login

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
> Added better templates for PR, bug reporting and feature request

- src/app/blog/[slug]/layout.tsx
- src/app/blog/[slug]/page.tsx
- src/app/blog/[slug]/utils/utils.ts
- src/app/layout.tsx
> BlogSchema added

- .github/workflows/smoke-test.yml
- .gitignore
- package.json
- pnpm-lock.yaml
> feat: add pnpm dev dependency

- apps/the_monkeys/.eslintrc.json
- apps/the_monkeys/package.json
- packages/ui/biome.json
Add rules and config changes in eslint and biome to fix the LF and CRLF issue
> Update ESLint configuration and format files for consistency

- apps/the_monkeys/next.config.mjs
- apps/the_monkeys/src/app/about/page.tsx
- apps/the_monkeys/src/constants/footer.ts
- Add about page
- Changed footer link to point to the about page.
> feat: add about page and update footer link to point to the About page

- apps/the_monkeys/src/app/auth/components/forms/LoginForm.tsx
- apps/the_monkeys/src/app/auth/login/page.tsx
Login form gets into loading state and resets the form, this change disables the form till the session validated
> fix:login-form-loading

- apps/the_monkeys/src/app/edit/[blogId]/page.tsx
Fix WS connection on draft edit
> fix: draft edit ws connection

- apps/the_monkeys/src/services/api/axiosFileInstance.ts
- apps/the_monkeys/src/services/api/axiosInstance.ts
- apps/the_monkeys/src/services/api/axiosInstanceNoAuth.ts
- apps/the_monkeys/src/services/api/axiosInstanceNoAuthV2.ts
- apps/the_monkeys/src/services/api/axiosInstanceV2.ts
- apps/the_monkeys/src/utils/clientInfo.ts
> Limit API Calls To Fetch IP

- apps/the_monkeys/src/app/blog/[slug]/page.tsx
- apps/the_monkeys/src/app/layout.tsx
- apps/the_monkeys/src/components/AdSense/AdUnit.tsx
> created slot Adunit added on specific pages only not on entire routes

- apps/the_monkeys/src/app/[username]/layout.tsx
- apps/the_monkeys/src/app/feed/layout.tsx
- apps/the_monkeys/src/app/layout.tsx
- apps/the_monkeys/src/app/sitemap.ts
> Person Schema added

- apps/the_monkeys/src/app/layout.tsx
> Microsoft clarity integration

- apps/the_monkeys/next.config.mjs
- apps/the_monkeys/src/app/feed/layout.tsx
- apps/the_monkeys/src/app/layout.tsx
- apps/the_monkeys/src/app/page.tsx
- apps/the_monkeys/src/components/blog/buttons/BookmarkButton.tsx
- apps/the_monkeys/src/hooks/profile/useProfileImage.ts
> Feed Route to Home route

- apps/the_monkeys/CONFIGURE.md
- apps/the_monkeys/src/app/about/page.tsx
- apps/the_monkeys/src/app/feed/page.tsx
- apps/the_monkeys/src/app/globals.css
- apps/the_monkeys/src/app/page.tsx
- apps/the_monkeys/src/components/branding/featuresGrid/AI.tsx
- apps/the_monkeys/src/components/branding/featuresGrid/CollaborativeWriting.tsx
- apps/the_monkeys/src/components/branding/featuresGrid/Snapshot.tsx
- apps/the_monkeys/src/components/branding/featuresGrid/VersionControl.tsx
- apps/the_monkeys/src/components/branding/membersGrid/index.tsx
- apps/the_monkeys/src/components/icon.tsx
- apps/the_monkeys/src/components/layout/navbar/NotificationDropdown.tsx
- apps/the_monkeys/src/components/layout/navbar/profileDropdown.tsx
- apps/the_monkeys/src/components/social/SocialSnapshotDialog.tsx
- apps/the_monkeys/src/constants/team.ts
- Updated Dave to Founder & Lead Backend Engineer
- Updated Piyush to Lead Maintainer & Frontend Engineer
- Updated Rahul to Lead Growth Marketing Engineer & Frontend Engineer
- Updated Tanishq to Fullstack Developer & Researcher
- Added Shinu as AI Engineer & Maintainer
- Commented out upcoming member placeholders
> Update team roles and add new team member
